### ISSUE TITLE
无法设置快捷键

### ISSUE THREAD

**Issue by 06ly6** [Enaium/sdv-mod-KeyBindUI#3]

**Comment by 06ly6** [comment]
![348925799-1287e60f-630f-41ce-a460-b037bf05cfac](https://github.com/user-attachments/assets/cce8b4c5-d256-4f1b-91f2-955d0761a2ce)

**Comment by 06ly6** [comment]
您要是忙的话，慢慢解决就行了，对于我们使用者来说只是不方便点，无伤大雅

**Comment by 06ly6** [comment]
您要是忙的话，慢慢解决就行了，对于我们使用者来说只是不方便点，无伤大雅

**Comment by Enaium** [comment]
都装了哪些mod

**Comment by Enaium** [comment]
一个一个排查一下，肯能是有的mod写的有问题导致我这个mod也出错了

**Comment by 06ly6** [comment]
发一下您的其他邮箱，我把压缩包发您，我这边每次启动都没显示冲突，不知道是什么原因，所以把压缩包发您，您这个邮箱收不了大于10MB的文件

**Comment by Enaium** [comment]
你试试，把其他的mod都先删了，启动一次用着没问题就加一个再试试

**Comment by 06ly6** [comment]
OK

**Comment by Enaium** [comment]
我更了个版本，现在你能在打开界面的时候在控制台看到是哪个mod有问题了
